image: ghcr.io/vaibhavp/django-actions/app
version: master-e3b285e
user: postgres
password: postgres
name: github-actions
postgresql:
  enabled: true
  auth.postgresPassword: postgres
  auth.database: